# -*- coding: utf-8 -*-
"""pengenalan_fungsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKBqCxyLarNK7th8Prgf6pHy9bgLx_7D
"""

# Membuat Fungsi
def salam():
    print("Hello, Selamat Pagi")  # Perbaikan penggunaan print pada Python 3

# Pemanggilan Fungsi
salam()

# Membuat Fungsi
def salam():
    print("Hello, Selamat Pagi")  # Perbaikan penggunaan print pada Python 3

# Pemanggilan Fungsi
salam()
salam()
salam()

# Membuat fungsi dengan parameter
def luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print("Luas segitiga: %f" % luas)  # Perbaikan print untuk Python 3

# Pemanggilan fungsi
luas_segitiga(4, 6)

# Membuat fungsi untuk menghitung luas persegi
def luas_persegi(sisi):
    luas = sisi * sisi
    return luas

# Pemanggilan fungsi
print("Luas persegi: %d" % luas_persegi(6))  # Perbaikan penggunaan print di Python 3

# rumus: sisi x sisi
def luas_persegi(sisi):
    luas = sisi * sisi
    return luas

# rumus: sisi x sisi x sisi
def volume_persegi(sisi):
    volume = luas_persegi(sisi) * sisi
    return volume  # Tambahkan return untuk mengembalikan nilai volume

# Membuat variabel global
nama = "Muhammad Rayanza al Maliki"
versi = "1.0.0"

def help():
    # Ini variabel lokal
    nama = "Programku"
    versi = "1.0.2"
    # Mengakses variabel lokal
    print("Nama: %s" % nama)
    print("Versi: %s" % versi)

# Mengakses variabel global
print("Nama: %s" % nama)
print("Versi: %s" % versi)

# Memanggil fungsi help()
help()