# -*- coding: utf-8 -*-
"""program_fungsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiLUuJZL8knOrEBzAZ2jia5KiC8XrfV0
"""

# Variabel global untuk menyimpan data Buku
buku = []

# Fungsi untuk menampilkan semua data
def show_data():
    if len(buku) <= 0:
        print("BELUM ADA DATA")  # Menggunakan tanda kurung pada print
    else:
        for indeks in range(len(buku)):
            print("[%d] %s" % (indeks, buku[indeks]))  # Menggunakan tanda kurung pada print


# Fungsi untuk menambah data
def insert_data():
    buku_baru = input("Judul Buku: ")  # raw_input diubah menjadi input
    buku.append(buku_baru)


# Fungsi untuk edit data
def edit_data():
    show_data()
    indeks = int(input("Inputkan ID buku: "))  # Mengubah input menjadi int
    if indeks >= len(buku):  # Ubah kondisi untuk memeriksa indeks
        print("ID salah")  # Tambahkan tanda kurung pada print
    else:
        judul_baru = input("Judul baru: ")  # raw_input diubah menjadi input
        buku[indeks] = judul_baru


# Fungsi untuk menghapus data
def delete_data():
    show_data()
    indeks = int(input("Inputkan ID buku: "))  # Mengubah input menjadi int
    if indeks >= len(buku):  # Gunakan '>=', karena indeks dimulai dari 0
        print("ID salah")  # Tambahkan tanda kurung pada print
    else:
        buku.remove(buku[indeks])  # Menghapus item berdasarkan indeks


# Fungsi untuk menampilkan menu
def show_menu():
    print("\n")
    print("----------- MENU ----------")
    print("[1] Show Data")
    print("[2] Insert Data")
    print("[3] Edit Data")
    print("[4] Delete Data")
    print("[5] Exit")

    menu = int(input("PILIH MENU> "))  # Mengubah input menjadi int
    print("\n")

    if menu == 1:
        show_data()
    elif menu == 2:
        insert_data()
    elif menu == 3:
        edit_data()
    elif menu == 4:
        delete_data()
    elif menu == 5:
        exit()
    else:
        print("Salah pilih!")  # Tambahkan tanda kurung pada print


if __name__ == "__main__":
    while True:
        show_menu()